# Codecov configuration for IT8951 e-paper Python driver
# Reference: https://docs.codecov.com/docs/codecovyml-reference

codecov:
  require_ci_to_pass: true
  max_report_age: 24  # hours

coverage:
  precision: 2  # 2 decimal places
  round: down   # round coverage down
  range: "80...100"  # coverage range for color coding (80-100% = green)

  status:
    # Overall project coverage
    project:
      default:
        target: 80%  # minimum acceptable coverage
        threshold: 1%  # allow 1% drop in coverage
        base: auto
        if_ci_failed: error
    
    # Coverage for changed code in PRs
    patch:
      default:
        target: 90%  # higher standard for new code
        threshold: 1%
        base: auto
        if_ci_failed: error

# Comments on pull requests
comment:
  layout: "reach,diff,flags,files"
  behavior: default  # update comment on new commits
  require_changes: false  # post comment even if no coverage change
  require_base: false
  require_head: true
  show_carryforward_flags: true

# Define coverage flags for different components
flags:
  unit:
    paths:
      - src/IT8951_ePaper_Py/
    carryforward: false
  integration:
    paths:
      - tests/
    carryforward: false
  ats-tests:
    paths:
      - src/IT8951_ePaper_Py/
    carryforward: true  # ATS needs carryforward for incremental coverage

# Ignore certain files from coverage
ignore:
  - "setup.py"
  - "**/__init__.py"
  - "**/test_*.py"
  - "tests/**"
  - "examples/**"
  - "stubs/**"
  - "docs/**"
  - "htmlcov/**"

# GitHub integration
github_checks:
  annotations: true

# Parsers configuration
parsers:
  v1:
    include_full_missed_files: true

# Automated Test Selection (ATS) configuration
cli:
  # Enable ATS for pull requests
  runners:
    python:
      # Use pytest as the test runner
      collect_tests_command:
        - poetry
        - run
        - pytest
        - --collect-only
        - -q
      # Label format for pytest
      label_format: "::testnode"
      # Enable test result processing
      process_test_results: true
      
# ATS settings
ats:
  # Enable ATS by default
  enabled: true
  # Minimum number of commits with coverage data before ATS activates
  min_commits: 3
  # Maximum age of coverage data to consider (in days)
  max_age: 30
  # Fallback to running all tests if ATS fails
  fallback_on_failure: true